In [201]:
import pandas as pd
import numpy as np

In [202]:
df_ICFES = pd.read_csv("icfes_dataset_2020_2.csv")

In [203]:
df_ICFES.head(5)

,ESTU_TIPODOCUMENTO,ESTU_NACIONALIDAD,ESTU_GENERO,ESTU_FECHANACIMIENTO,PERIODO,ESTU_CONSECUTIVO,ESTU_ESTUDIANTE,ESTU_PAIS_RESIDE,ESTU_TIENEETNIA,ESTU_DEPTO_RESIDE,...,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL,ESTU_INSE_INDIVIDUAL,ESTU_NSE_INDIVIDUAL,ESTU_NSE_ESTABLECIMIENTO,ESTU_ESTADOINVESTIGACION,ESTU_GENERACION-E
0,TI,SUIZA,F,2003 Mar 03 12:00:00 AM,20204,SB11202040211436,ESTUDIANTE,SUIZA,No,CUNDINAMARCA,...,55.0,81,A1,244,49,"54,88236473511",3.0,3.0,PUBLICAR,NO
1,PEP,VENEZUELA,M,2002 May 10 12:00:00 AM,20204,SB11202040433216,ESTUDIANTE,VENEZUELA,No,CUNDINAMARCA,...,33.0,6,A-,238,44,"49,2523109721",2.0,2.0,PUBLICAR,NO
2,TI,VENEZUELA,F,2003 Dec 14 12:00:00 AM,20204,SB11202040244180,ESTUDIANTE,VENEZUELA,No,CUNDINAMARCA,...,59.0,87,A2,325,94,"40,73367237969",1.0,3.0,PUBLICAR,GENERACION E - GRATUIDAD
3,CE,VENEZUELA,M,2003 Apr 12 12:00:00 AM,20204,SB11202040210971,ESTUDIANTE,VENEZUELA,No,CUNDINAMARCA,...,47.0,58,A-,238,45,"48,21795281652",2.0,3.0,PUBLICAR,NO
4,TI,COLOMBIA,F,2004 Mar 03 12:00:00 AM,20204,SB11202040235382,ESTUDIANTE,COLOMBIA,No,CUNDINAMARCA,...,43.0,40,A-,202,19,"60,91219196246",3.0,3.0,PUBLICAR,NO

In [204]:
df_ICFES.shape

(504872, 81)

In [205]:
df_ICFES.info()

<class 'pandas.DataFrame'>
RangeIndex: 504872 entries, 0 to 504871
Data columns (total 81 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   ESTU_TIPODOCUMENTO             504872 non-null  str
 1   ESTU_NACIONALIDAD              504872 non-null  str
 2   ESTU_GENERO                    504864 non-null  str
 3   ESTU_FECHANACIMIENTO           504872 non-null  str
 4   PERIODO                        504872 non-null  int64
 5   ESTU_CONSECUTIVO               504872 non-null  str
 6   ESTU_ESTUDIANTE                504872 non-null  str
 7   ESTU_PAIS_RESIDE               504872 non-null  str
 8   ESTU_TIENEETNIA                501879 non-null  str
 9   ESTU_DEPTO_RESIDE              504870 non-null  str
 10  ESTU_COD_RESIDE_DEPTO          504870 non-null  float64
 11  ESTU_MCPIO_RESIDE              504870 non-null  str
 12  ESTU_COD_RESIDE_MCPIO          504870 non-null  float64
 13  FAMI_ESTRATOVIVIENDA           487920 non-null  str
 14  FAMI_PERSONASHOGAR             489699 non-null  str
 15  FAMI_CUARTOSHOGAR              489033 non-null  str
 16  FAMI_EDUCACIONPADRE            491882 non-null  str
 17  FAMI_EDUCACIONMADRE            491386 non-null  str
 18  FAMI_TRABAJOLABORPADRE         485181 non-null  str
 19  FAMI_TRABAJOLABORMADRE         487273 non-null  str
 20  FAMI_TIENEINTERNET             491207 non-null  str
 21  FAMI_TIENESERVICIOTV           489433 non-null  str
 22  FAMI_TIENECOMPUTADOR           484678 non-null  str
 23  FAMI_TIENELAVADORA             488640 non-null  str
 24  FAMI_TIENEHORNOMICROOGAS       487730 non-null  str
 25  FAMI_TIENEAUTOMOVIL            487063 non-null  str
 26  FAMI_TIENEMOTOCICLETA          487786 non-null  str
 27  FAMI_TIENECONSOLAVIDEOJUEGOS   487394 non-null  str
 28  FAMI_NUMLIBROS                 491029 non-null  str
 29  FAMI_COMELECHEDERIVADOS        491244 non-null  str
 30  FAMI_COMECARNEPESCADOHUEVO     489566 non-null  str
 31  FAMI_COMECEREALFRUTOSLEGUMBRE  484609 non-null  str
 32  FAMI_SITUACIONECONOMICA        488558 non-null  str
 33  ESTU_DEDICACIONLECTURADIARIA   490391 non-null  str
 34  ESTU_DEDICACIONINTERNET        490246 non-null  str
 35  ESTU_HORASSEMANATRABAJA        487888 non-null  str
 36  ESTU_TIPOREMUNERACION          487226 non-null  str
 37  COLE_CODIGO_ICFES              504872 non-null  int64
 38  COLE_COD_DANE_ESTABLECIMIENTO  504872 non-null  int64
 39  COLE_NOMBRE_ESTABLECIMIENTO    504872 non-null  str
 40  COLE_GENERO                    504872 non-null  str
 41  COLE_NATURALEZA                504872 non-null  str
 42  COLE_CALENDARIO                504872 non-null  str
 43  COLE_BILINGUE                  421865 non-null  str
 44  COLE_CARACTER                  490695 non-null  str
 45  COLE_COD_DANE_SEDE             504872 non-null  int64
 46  COLE_NOMBRE_SEDE               504872 non-null  str
 47  COLE_SEDE_PRINCIPAL            504872 non-null  str
 48  COLE_AREA_UBICACION            504872 non-null  str
 49  COLE_JORNADA                   504872 non-null  str
 50  COLE_COD_MCPIO_UBICACION       504872 non-null  int64
 51  COLE_MCPIO_UBICACION           504872 non-null  str
 52  COLE_COD_DEPTO_UBICACION       504872 non-null  int64
 53  COLE_DEPTO_UBICACION           504872 non-null  str
 54  ESTU_PRIVADO_LIBERTAD          504872 non-null  str
 55  ESTU_COD_MCPIO_PRESENTACION    504664 non-null  float64
 56  ESTU_MCPIO_PRESENTACION        504664 non-null  str
 57  ESTU_DEPTO_PRESENTACION        504664 non-null  str
 58  ESTU_COD_DEPTO_PRESENTACION    504664 non-null  float64
 59  PUNT_LECTURA_CRITICA           504872 non-null  int64
 60  PERCENTIL_LECTURA_CRITICA      504872 non-null  int64
 61  DESEMP_LECTURA_CRITICA         504872 non-null  int64
 62  PUNT_MATEMATICAS               504872 non-null  int64
 63  PERCENTIL_MATEMATICAS          504872 non-null  int64
 64  DESEMP_MATEMATICAS             504872 non-null  int64
 65  PUNT_C_NATURALES               504872 non-null  int64
 66  PERCENTIL_C_NATURALES          504872 non-null  int64
 67  DESEMP_C_NATURALES             504872 non-null  int64
 68  PUNT_SOCIALES_CIUDADANAS       504872 non-null  int64
 69  PERCENTIL_SOCIALES_CIUDADANAS  504872 non-null  int64
 70  DESEMP_SOCIALES_CIUDADANAS     504872 non-null  int64
 71  PUNT_INGLES                    504538 non-null  float64
 72  PERCENTIL_INGLES               504872 non-null  int64
 73  DESEMP_INGLES                  504872 non-null  str
 74  PUNT_GLOBAL                    504872 non-null  int64
 75  PERCENTIL_GLOBAL               504872 non-null  int64
 76  ESTU_INSE_INDIVIDUAL           490927 non-null  str
 77  ESTU_NSE_INDIVIDUAL            490927 non-null  float64
 78  ESTU_NSE_ESTABLECIMIENTO       504823 non-null  float64
 79  ESTU_ESTADOINVESTIGACION       504872 non-null  str
 80  ESTU_GENERACION-E              504872 non-null  str
dtypes: float64(7), int64(21), str(53)
memory usage: 604.5 MB

Agrupando las columnas en diferentes categorías

In [206]:
estu_cols = [col for col in df_ICFES.columns if 'ESTU_' in col]
fami_cols = [col for col in df_ICFES.columns if 'FAMI_' in col]
cole_cols = [col for col in df_ICFES.columns if 'COLE_' in col]
result_cols = [col for col in df_ICFES.columns if not col.startswith(('COLE_', 'ESTU_', 'FAMI_'))]

Primero analizaremos las columnas relacionadas al estudiante

In [207]:
df_ICFES[estu_cols].isna().sum()

ESTU_TIPODOCUMENTO                  0
ESTU_NACIONALIDAD                   0
ESTU_GENERO                         8
ESTU_FECHANACIMIENTO                0
ESTU_CONSECUTIVO                    0
ESTU_ESTUDIANTE                     0
ESTU_PAIS_RESIDE                    0
ESTU_TIENEETNIA                  2993
ESTU_DEPTO_RESIDE                   2
ESTU_COD_RESIDE_DEPTO               2
ESTU_MCPIO_RESIDE                   2
ESTU_COD_RESIDE_MCPIO               2
ESTU_DEDICACIONLECTURADIARIA    14481
ESTU_DEDICACIONINTERNET         14626
ESTU_HORASSEMANATRABAJA         16984
ESTU_TIPOREMUNERACION           17646
ESTU_PRIVADO_LIBERTAD               0
ESTU_COD_MCPIO_PRESENTACION       208
ESTU_MCPIO_PRESENTACION           208
ESTU_DEPTO_PRESENTACION           208
ESTU_COD_DEPTO_PRESENTACION       208
ESTU_INSE_INDIVIDUAL            13945
ESTU_NSE_INDIVIDUAL             13945
ESTU_NSE_ESTABLECIMIENTO           49
ESTU_ESTADOINVESTIGACION            0
ESTU_GENERACION-E                   0
dtype: int64

In [208]:
for col in df_ICFES[estu_cols].select_dtypes(include='str').columns:
    print(col)
    print(df_ICFES[col].unique())

ESTU_TIPODOCUMENTO
<ArrowStringArray>
['TI', 'PEP', 'CE', 'CC', 'NES', 'CR', 'PE', 'PC', 'V', 'NUIP', 'RC']
Length: 11, dtype: str
ESTU_NACIONALIDAD
<ArrowStringArray>
[                          'SUIZA',                       'VENEZUELA',
                        'COLOMBIA',                         'ECUADOR',
                       'GUATEMALA',                            'PERÚ',
                  'ESTADOS UNIDOS',                          'MÉXICO',
                          'ITALIA',                   'COREA DEL SUR',
                         'URUGUAY', 'ESTADOS FEDERADOS DE MICRONESIA',
                         'BOLIVIA',                          'PANAMÁ',
                           'CHILE',            'REPÚBLICA DOMINICANA',
                     'EL SALVADOR',                          'BRASIL',
                       'ARGENTINA',                          'ESPAÑA',
                 'WALLIS Y FUTUNA',                      'CABO VERDE',
                         'VANUATU',                         'VIETNAM',
                         'FRANCIA',                        'HONDURAS',
                            'CUBA',                           'JAPÓN',
                  'ARABIA SAUDITA',                           'RUSIA',
                           'HAITI',                          'EGIPTO',
                            'IRÁN',                     'REINO UNIDO',
                      'COSTA RICA',                           'CHINA',
                        'LITUANIA',                         'CURAZAO',
                           'ARUBA',                        'PARAGUAY',
                       'NICARAGUA',                        'ALEMANIA',
                          'CANADÁ',                 'COREA DEL NORTE',
                         'TURQUÍA',          'PAÍSES BAJOS - HOLANDA',
                            'OMÁN']
Length: 47, dtype: str
ESTU_GENERO
<ArrowStringArray>
['F', 'M', nan]
Length: 3, dtype: str
ESTU_FECHANACIMIENTO
<ArrowStringArray>
['2003 Mar 03 12:00:00 AM', '2002 May 10 12:00:00 AM',
 '2003 Dec 14 12:00:00 AM', '2003 Apr 12 12:00:00 AM',
 '2004 Mar 03 12:00:00 AM', '2002 Dec 14 12:00:00 AM',
 '2003 Sep 18 12:00:00 AM', '2003 Mar 31 12:00:00 AM',
 '2002 Jun 17 12:00:00 AM', '2002 Sep 09 12:00:00 AM',
 ...
 '1965 Jul 02 12:00:00 AM', '1980 Apr 07 12:00:00 AM',
 '1986 Jan 29 12:00:00 AM', '2013 Mar 08 12:00:00 AM',
 '1995 Oct 16 12:00:00 AM', '1972 Jun 09 12:00:00 AM',
 '1977 May 12 12:00:00 AM', '1971 Jan 19 12:00:00 AM',
 '1969 Mar 31 12:00:00 AM', '1996 Oct 19 12:00:00 AM']
Length: 9603, dtype: str
ESTU_CONSECUTIVO
<ArrowStringArray>
['SB11202040211436', 'SB11202040433216', 'SB11202040244180',
 'SB11202040210971', 'SB11202040235382', 'SB11202040237578',
 'SB11202040252472', 'SB11202040251547', 'SB11202040305779',
 'SB11202040305725',
 ...
 'SB11202040115228', 'SB11202040112449', 'SB11202040547511',
 'SB11202040434267', 'SB11202040115424', 'SB11202040105446',
 'SB11202040168415', 'SB11202040185843', 'SB11202040168607',
 'SB11202040525571']
Length: 504872, dtype: str
ESTU_ESTUDIANTE
<ArrowStringArray>
['ESTUDIANTE']
Length: 1, dtype: str
ESTU_PAIS_RESIDE
<ArrowStringArray>
[                          'SUIZA',                       'VENEZUELA',
                        'COLOMBIA',                         'ECUADOR',
                       'GUATEMALA',                            'PERÚ',
                  'ESTADOS UNIDOS',                          'MÉXICO',
                          'ITALIA',                   'COREA DEL SUR',
                         'URUGUAY', 'ESTADOS FEDERADOS DE MICRONESIA',
                         'BOLIVIA',                          'PANAMÁ',
                           'CHILE',            'REPÚBLICA DOMINICANA',
                     'EL SALVADOR',                          'BRASIL',
                       'ARGENTINA',                          'ESPAÑA',
                 'WALLIS Y FUTUNA',                      'CABO VERDE',
                         'VANUATU',                         'VIETNAM',
                         'FRANCIA',                        'HONDURAS',
                            'CUBA',                           'JAPÓN',
                  'ARABIA SAUDITA',                           'RUSIA',
                           'HAITI',                          'EGIPTO',
                            'IRÁN',                     'REINO UNIDO',
                      'COSTA RICA',                           'CHINA',
                        'LITUANIA',                         'CURAZAO',
                           'ARUBA',                        'PARAGUAY',
                       'NICARAGUA',                        'ALEMANIA',
                          'CANADÁ',                 'COREA DEL NORTE',
                         'TURQUÍA',          'PAÍSES BAJOS - HOLANDA',
                            'OMÁN']
Length: 47, dtype: str
ESTU_TIENEETNIA
<ArrowStringArray>
['No', 'Si', nan]
Length: 3, dtype: str
ESTU_DEPTO_RESIDE
<ArrowStringArray>
[   'CUNDINAMARCA',       'ANTIOQUIA',         'BOLIVAR', 'NORTE SANTANDER',
         'CAQUETA',       'RISARALDA',       'SANTANDER',       'MAGDALENA',
          'BOGOTÁ',          'CALDAS',           'VALLE',         'QUINDIO',
           'SUCRE',       'ATLANTICO',           'HUILA',      'LA GUAJIRA',
         'CORDOBA',          'NARIÑO',            'META',           'CAUCA',
        'CASANARE',        'GUAVIARE',        'PUTUMAYO',           'CESAR',
           'CHOCO',          'ARAUCA',         'VICHADA',          'TOLIMA',
          'BOYACA',        'AMAZONAS',      'EXTRANJERO',      'SAN ANDRES',
          'VAUPES',         'GUAINIA',               nan]
Length: 35, dtype: str
ESTU_MCPIO_RESIDE
<ArrowStringArray>
[                'CAJICÁ',                  'TABIO',               'RIONEGRO',
    'CARTAGENA DE INDIAS',               'PAMPLONA',              'FLORENCIA',
                'PEREIRA',        'BARRANCABERMEJA', 'SAN VICENTE DE CHUCURÍ',
                'MAHATES',
 ...
            'SAN JOAQUÍN',      'VALLE DE SAN JUAN',            'GÓMEZ PLATA',
       'VIGÍA DEL FUERTE',                'MATANZA',                 'SURATÁ',
             'CALIFORNIA',               'ZAPATOCA',                  'VIOTÁ',
                 'AMALFI']
Length: 1032, dtype: str
ESTU_DEDICACIONLECTURADIARIA
<ArrowStringArray>
[        '30 minutos o menos', 'No leo por entretenimiento',
      'Entre 30 y 60 minutos',          'Entre 1 y 2 horas',
             'Más de 2 horas',                          nan]
Length: 6, dtype: str
ESTU_DEDICACIONINTERNET
<ArrowStringArray>
[       'Más de 3 horas',    '30 minutos o menos',     'Entre 1 y 3 horas',
    'No Navega Internet', 'Entre 30 y 60 minutos',                     nan]
Length: 6, dtype: str
ESTU_HORASSEMANATRABAJA
<ArrowStringArray>
[                  '0', 'Entre 11 y 20 horas',   'Menos de 10 horas',
 'Entre 21 y 30 horas',     'Más de 30 horas',                   nan]
Length: 6, dtype: str
ESTU_TIPOREMUNERACION
<ArrowStringArray>
['No', 'Si, en efectivo', 'Si, en efectivo y especie', nan, 'Si, en especie']
Length: 5, dtype: str
ESTU_PRIVADO_LIBERTAD
<ArrowStringArray>
['N', 'S']
Length: 2, dtype: str
ESTU_MCPIO_PRESENTACION
<ArrowStringArray>
[             'CAJICÁ',            'RIONEGRO', 'CARTAGENA DE INDIAS',
            'PAMPLONA',           'FLORENCIA',             'PEREIRA',
     'BARRANCABERMEJA',           'CIMITARRA',               'URRAO',
             'CIÉNAGA',
 ...
            'TENERIFE',             'MATANZA',            'ZAPATOCA',
 'SAN JUAN DE RIOSECO',               'PAIPA',   'SAN LUIS DE SINCÉ',
    'VIGÍA DEL FUERTE',               'VIOTÁ',              'MEDINA',
              'AMALFI']
Length: 485, dtype: str
ESTU_DEPTO_PRESENTACION
<ArrowStringArray>
[   'CUNDINAMARCA',       'ANTIOQUIA',         'BOLIVAR', 'NORTE SANTANDER',
         'CAQUETA',       'RISARALDA',       'SANTANDER',       'MAGDALENA',
          'BOGOTÁ',          'CALDAS',           'VALLE',         'QUINDIO',
           'SUCRE',       'ATLANTICO',           'HUILA',      'LA GUAJIRA',
         'CORDOBA',          'NARIÑO',            'META',           'CAUCA',
        'CASANARE',        'GUAVIARE',        'PUTUMAYO',           'CESAR',
           'CHOCO',          'ARAUCA',         'VICHADA',          'TOLIMA',
          'BOYACA',        'AMAZONAS',      'SAN ANDRES',          'VAUPES',
               nan,         'GUAINIA']
Length: 34, dtype: str
ESTU_INSE_INDIVIDUAL
<ArrowStringArray>
['54,88236473511',  '49,2523109721', '40,73367237969', '48,21795281652',
 '60,91219196246', '43,23995868425', '60,89435653878', '64,60025101502',
 '50,24410587994', '43,71258765692',
 ...
 '46,74931951686', '64,84490918643', '57,56805159394', '59,29375324211',
  '52,4096403338', '67,94793534218', '61,45761144467', '45,31144885111',
 '38,12472866627', '53,58644335771']
Length: 455003, dtype: str
ESTU_ESTADOINVESTIGACION
<ArrowStringArray>
['PUBLICAR', 'VALIDEZ OFICINA JURÍDICA']
Length: 2, dtype: str
ESTU_GENERACION-E
<ArrowStringArray>
[                                     'NO',
                'GENERACION E - GRATUIDAD',
      'GENERACION E - EXCELENCIA NACIONAL',
 'GENERACION E - EXCELENCIA DEPARTAMENTAL']
Length: 4, dtype: str

De estas columnas, seleccionaremos solo las más importantes.

NSE significa nivel socio económico, 
TIENEETNIA - solo es un sí/no pero no se específica la ETNIA, por lo que no es significativo.
TIPODOCUMENTO, ESTUDIANTE, GENERACION-E, ESTADOINVESTIGACION no son relevantes. 

ESTU_NACIONALIDAD, ESTU_GENERO, ESTU_CONSECUTIVO ESTU_FECHANACIMIENTO, ESTU_PAIS_RESIDE, ESTU_DEPTO_RESIDE, ESTU_MCPIO_RESIDE, ESTU_NSE_INDIVIDUAL, ESTU_NSE_ESTABLECIMIENTO

serán las columnas de interés

In [209]:
estu_selected_cols = ["ESTU_NACIONALIDAD", "ESTU_GENERO","ESTU_FECHANACIMIENTO","ESTU_PAIS_RESIDE", "ESTU_DEPTO_RESIDE", "ESTU_MCPIO_RESIDE", "ESTU_NSE_INDIVIDUAL", "ESTU_NSE_ESTABLECIMIENTO"]

In [210]:
df_ICFES[estu_selected_cols].isna().sum()

ESTU_NACIONALIDAD               0
ESTU_GENERO                     8
ESTU_FECHANACIMIENTO            0
ESTU_PAIS_RESIDE                0
ESTU_DEPTO_RESIDE               2
ESTU_MCPIO_RESIDE               2
ESTU_NSE_INDIVIDUAL         13945
ESTU_NSE_ESTABLECIMIENTO       49
dtype: int64

Como los nulos de GENERO, DEPTO_RESIDE, NSE_ESTABLECIMIENTO, MCPIO_RESIDE son pocos, se eliminan, mientras la columna ESTU_NSE_INDIVIDUAL tiene una población significativa.

In [211]:
df_ICFES.dropna(subset=['ESTU_NSE_ESTABLECIMIENTO','ESTU_GENERO','ESTU_DEPTO_RESIDE', 'ESTU_MCPIO_RESIDE'], inplace=True)

In [212]:
df_ICFES[estu_selected_cols].isna().sum()

ESTU_NACIONALIDAD               0
ESTU_GENERO                     0
ESTU_FECHANACIMIENTO            0
ESTU_PAIS_RESIDE                0
ESTU_DEPTO_RESIDE               0
ESTU_MCPIO_RESIDE               0
ESTU_NSE_INDIVIDUAL         13894
ESTU_NSE_ESTABLECIMIENTO        0
dtype: int64

In [213]:
df_ICFES["ESTU_FECHANACIMIENTO"] = pd.to_datetime(df_ICFES['ESTU_FECHANACIMIENTO'], format='%Y %b %d %I:%M:%S %p')

In [214]:
df_ICFES[estu_selected_cols].info()

<class 'pandas.DataFrame'>
Index: 504813 entries, 0 to 504871
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ESTU_NACIONALIDAD         504813 non-null  str
 1   ESTU_GENERO               504813 non-null  str
 2   ESTU_FECHANACIMIENTO      504813 non-null  datetime64[us]
 3   ESTU_PAIS_RESIDE          504813 non-null  str
 4   ESTU_DEPTO_RESIDE         504813 non-null  str
 5   ESTU_MCPIO_RESIDE         504813 non-null  str
 6   ESTU_NSE_INDIVIDUAL       490919 non-null  float64
 7   ESTU_NSE_ESTABLECIMIENTO  504813 non-null  float64
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 51.5 MB

Conversión a SQL:

In [215]:
fami_selected_cols = ["FAMI_ESTRATOVIVIENDA", "FAMI_TIENEINTERNET", "FAMI_TIENECOMPUTADOR"]

In [216]:
print(getSQLTable("estudiantes", "ESTU_",estu_selected_cols, df_ICFES))

CREATE TABLE IF NOT EXISTS estudiantes(
id INT AUTO_INCREMENT PRIMARY KEY,
nacionalidad VARCHAR(255),
genero VARCHAR(255),
fechanacimiento DATE,
pais_reside VARCHAR(255),
depto_reside VARCHAR(255),
mcpio_reside VARCHAR(255),
nse_individual REAL,
nse_establecimiento REAL
);

In [217]:
df_ICFES[fami_cols].isna().sum()

FAMI_ESTRATOVIVIENDA             16901
FAMI_PERSONASHOGAR               15121
FAMI_CUARTOSHOGAR                15787
FAMI_EDUCACIONPADRE              12939
FAMI_EDUCACIONMADRE              13435
FAMI_TRABAJOLABORPADRE           19639
FAMI_TRABAJOLABORMADRE           17547
FAMI_TIENEINTERNET               13614
FAMI_TIENESERVICIOTV             15389
FAMI_TIENECOMPUTADOR             20142
FAMI_TIENELAVADORA               16180
FAMI_TIENEHORNOMICROOGAS         17090
FAMI_TIENEAUTOMOVIL              17757
FAMI_TIENEMOTOCICLETA            17034
FAMI_TIENECONSOLAVIDEOJUEGOS     17426
FAMI_NUMLIBROS                   13792
FAMI_COMELECHEDERIVADOS          13577
FAMI_COMECARNEPESCADOHUEVO       15255
FAMI_COMECEREALFRUTOSLEGUMBRE    20212
FAMI_SITUACIONECONOMICA          16262
dtype: int64

In [218]:
df_ICFES.FAMI_ESTRATOVIVIENDA.unique()

<ArrowStringArray>
[  'Estrato 2',   'Estrato 3',   'Estrato 1', 'Sin Estrato',   'Estrato 5',
   'Estrato 6',   'Estrato 4',           nan]
Length: 8, dtype: str

In [219]:
df_ICFES[fami_selected_cols].head(5)

  FAMI_ESTRATOVIVIENDA FAMI_TIENEINTERNET FAMI_TIENECOMPUTADOR
0            Estrato 2                 Si                   Si
1            Estrato 3                 Si                   No
2            Estrato 1                 No                   No
3          Sin Estrato                 Si                   No
4            Estrato 5                 Si                   Si

In [220]:
df_ICFES["FAMI_ESTRATOVIVIENDA"] = df_ICFES["FAMI_ESTRATOVIVIENDA"].str.replace("Estrato ", "").replace("Sin Estrato", np.nan).astype(float)

In [221]:
df_ICFES["FAMI_ESTRATOVIVIENDA"].head(5)

0    2.0
1    3.0
2    1.0
3    NaN
4    5.0
Name: FAMI_ESTRATOVIVIENDA, dtype: float64

In [222]:
df_ICFES["FAMI_TIENEINTERNET"] = df_ICFES["FAMI_TIENEINTERNET"].map({"Si": 1, "No": 0})
df_ICFES["FAMI_TIENECOMPUTADOR"] = df_ICFES["FAMI_TIENECOMPUTADOR"].map({"Si": 1, "No": 0})

In [223]:
df_ICFES[result_cols].head(5)

,PERIODO,PUNT_LECTURA_CRITICA,PERCENTIL_LECTURA_CRITICA,DESEMP_LECTURA_CRITICA,PUNT_MATEMATICAS,PERCENTIL_MATEMATICAS,DESEMP_MATEMATICAS,PUNT_C_NATURALES,PERCENTIL_C_NATURALES,DESEMP_C_NATURALES,PUNT_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PUNT_INGLES,PERCENTIL_INGLES,DESEMP_INGLES,PUNT_GLOBAL,PERCENTIL_GLOBAL
0,20204,54,57,3,65,89,3,41,29,2,33,11,1,55.0,81,A1,244,49
1,20204,57,67,3,43,26,2,46,45,2,49,55,2,33.0,6,A-,238,44
2,20204,59,73,3,72,97,4,63,92,3,68,95,3,59.0,87,A2,325,94
3,20204,47,32,2,55,64,3,46,43,2,43,38,2,47.0,58,A-,238,45
4,20204,37,8,2,48,42,2,44,38,2,32,7,1,43.0,40,A-,202,19

In [224]:
dtypes_sql = {'str':'VARCHAR(255)','int64':'INT','float64':'REAL','datetime64[us]':'DATE'}
def getTypes(cols, prefix, df):    
    types = {}
    for col in cols:
        clean_col = col.replace(prefix, "")
        types[clean_col] = str(df[col].dtype)
    return types
    
def getSQLTable(table, prefix, cols, df):
    types = getTypes(cols, prefix, df) 
    SQL_table = f'''CREATE TABLE IF NOT EXISTS {table}( 
id INT AUTO_INCREMENT PRIMARY KEY'''
        
    for col, dtype in types.items():
        SQL_table += f",\n{col.lower()} {dtypes_sql[dtype]}"
    SQL_table += '\n);'
    return SQL_table

In [225]:
tables_dict = [{
    'name': 'estudiantes',
    'prefix': 'ESTU_',
    'cols': estu_selected_cols},
               {
    'name': 'familias',
    'prefix': 'FAMI_',
    'cols': fami_selected_cols}
              ]
for table in tables_dict:
   print(getSQLTable(table["name"], table["prefix"], table["cols"], df_ICFES))

CREATE TABLE IF NOT EXISTS estudiantes(
id INT AUTO_INCREMENT PRIMARY KEY,
nacionalidad VARCHAR(255),
genero VARCHAR(255),
fechanacimiento DATE,
pais_reside VARCHAR(255),
depto_reside VARCHAR(255),
mcpio_reside VARCHAR(255),
nse_individual REAL,
nse_establecimiento REAL
);
CREATE TABLE IF NOT EXISTS familias(
id INT AUTO_INCREMENT PRIMARY KEY,
estratovivienda REAL,
tieneinternet REAL,
tienecomputador REAL
);